### PR TITLE
Import ruby onigmo patches

### PR DESCRIPTION
**Pull request by cosmo0920**
I imported several patches for ruby bundled onigmo.
BTW, the recent ruby bundled onigmo starts to implement matching cache regular expression mechanism that mitigates for ReDOS.
This imported patch set is not included those changes yet.

Related to #5.

### CODE REVIEW

**Comment by edsiper** [comment]
@cosmo0920 is there a way to run the Ruby unit tests on top of these changes ?

**Comment by cosmo0920** [comment]
Unfortunately, there is no way to run Ruby's unit tests.
Ruby's onigmo should compile with Ruby's C extension and run against Ruby's unit tests.
Onigmo upstream does not have a way to handle Ruby's unit tests.

**Comment by edsiper** [comment]
@cosmo0920 are these changes safe to merge ?

**Comment by cosmo0920** [comment]
Yes. There is no breakage on unit tests (C and Python test cases).

**Pull request merged**
